#!/bin/bash

read -p "Entrez un un fichier à stage: " addMessage
read -p "Entrez un message de commit: " commitMessage

if [ -z "$commitMessage" ]; then
	echo "Veuillez renseigner un message pour le commit !"
	exit 1
fi

git add "$addMessage"
git status
git commit -m "$commitMessage"
